/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Countup: typeof import('./../src/components/countup.vue')['default']
    Header: typeof import('./../src/components/header.vue')['default']
    MessageBox: typeof import('./../src/components/MessageBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/sidebar.vue')['default']
    Stream: typeof import('./../src/components/stream.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TableCustom: typeof import('./../src/components/table-custom.vue')['default']
    TableDetail: typeof import('./../src/components/table-detail.vue')['default']
    TableEdit: typeof import('./../src/components/table-edit.vue')['default']
    TableSearch: typeof import('./../src/components/table-search.vue')['default']
    Tabs: typeof import('./../src/components/tabs.vue')['default']
    UpLoadPic: typeof import('./../src/components/upLoadPic/index.vue')['default']
    XtDialog: typeof import('./../src/components/XtDialog/index.vue')['default']
  }
}
